# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InnostaxBoilerplate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for InnostaxBoilerplate

  pod 'Bolts'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'


  target 'InnostaxBoilerplateTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'InnostaxBoilerplate-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for InnostaxBoilerplate-tvOS

  target 'InnostaxBoilerplate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
