# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'InnostaxBoilerplate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for InnostaxBoilerplate

  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Messaging'
  pod 'Firebase/Firestore'
  
  target 'InnostaxBoilerplateTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'InnostaxBoilerplate-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for InnostaxBoilerplate-tvOS

  target 'InnostaxBoilerplate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
